hosts:
  f-engine: ['alpaca-1']

arp:
  xb-engine:
    10.17.16.1:  0x02a2020002A1
    10.17.16.1:  0xb03fd29f0eca
    10.17.16.2:  0xb03fd29f0ecb
    10.17.16.3:  0xb03fd29f212a
    10.17.16.4:  0xb03fd29f212b
    10.17.16.5:  0x0202020002a3
    10.17.16.6:  0x0202020002a4
    10.17.16.7:  0x0202020002a5
    10.17.16.8:  0x0202020002a6
    10.17.16.9:  0x0202020002a7
    10.17.16.10: 0x6cb311213386
    10.17.16.11: 0x1070fd10d304
    10.17.16.12: 0xb83fd29f213a
    10.17.16.13: 0x020202000213
    10.17.16.14: 0x020202000214
    10.17.16.15: 0x020202000215
    10.17.16.16: 0x020202000216
    10.17.16.17: 0x020202000217
    10.17.16.18: 0x020202000218
    10.17.16.19: 0x020202000219
    10.17.16.20: 0x020202000220
    10.17.16.21: 0x020202000221
    10.17.16.22: 0x0c42a10b9c72



  f-engine:
    10.17.16.1:  0x02a2020002A1
    10.17.16.60: 0x02a2020002fa
    10.17.16.61: 0x02a2020002fb
